name: Rust

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd convoy && cargo build -r --verbose
    - name: Run tests
      run: cd convoy && cargo test --verbose
    - name: Release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cd convoy && gh release create ${{ github.ref_name }} \
            target/release/convoy \
            --title "Convoy release ${{ github.ref_name }}" \
            --generate-notes
