name: Release Convoy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install deps
      run: sudo apt update && sudo apt install -y libelf-dev tcpdump libpcap-dev
    - name: Build -> Test -> Release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd convoy-ebpf
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        cargo install bpf-linker
        cargo build -r --verbose
        cd ..
        cd convoy
        cargo build -r --verbose
        cargo test --verbose
        git fetch --tags origin --force
        LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
        VERSION=${LATEST_TAG#v}
        BASE_VERSION=$(echo "$VERSION" | cut -d. -f1-2)
        PATCH_VERSION=$(echo "$VERSION" | cut -d. -f3)
        NEXT_TAG="v${BASE_VERSION}.$((PATCH_VERSION + 1))"
        gh release create "$NEXT_TAG" target/release/convoy target/release/con-reader --title "Convoy release "$NEXT_TAG" (x86)" --generate-notes
