name: Release Convoy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt update && sudo apt install -y libelf-dev tcpdump libpcap-dev
    - name: Build -> Test -> Release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cd convoy && cargo build -r --verbose && cargo test --verbose && gh release create ${{ github.ref_name }} target/release/convoy --title "Convoy release ${{ github.ref_name }} (x86)" --generate-notes
